name: CI

on:
  push:
    branches: [ '*' ]  # Run on all branches
  pull_request:
    branches: [ '*' ]  # Run on PRs to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        yarn add --dev eslint@8.57.1 --exact
    
    - name: Run linting
      run: yarn lint || true
    
    - name: Build
      run: yarn build
      
    - name: Run tests
      run: yarn test
